language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
# ignore: E501 line too long, W503 line break before binary operator, W504 line break after binary operator
  - pycodestyle . --ignore=E501,W503,W504
  - python -m unittest discover -v
  - coverage run -m unittest discover
after_success:
  - coveralls