language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
# ignore: E501 line too long
  - pycodestyle . --ignore=E501
  - python -m unittest discover -v
  - coverage run -m unittest discover
after_success:
  - coveralls